// Code generated by "stringer -type=Type -linecomment"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Illegal-1]
	_ = x[EOF-2]
	_ = x[If-3]
	_ = x[Is-4]
	_ = x[For-5]
	_ = x[Switch-6]
	_ = x[Case-7]
	_ = x[Default-8]
	_ = x[In-9]
	_ = x[Stop-10]
	_ = x[Next-11]
	_ = x[While-12]
	_ = x[Else-13]
	_ = x[Fun-14]
	_ = x[None-15]
	_ = x[Catch-16]
	_ = x[Block-17]
	_ = x[Object-18]
	_ = x[Return-19]
	_ = x[Super-20]
	_ = x[Or-21]
	_ = x[And-22]
	_ = x[This-23]
	_ = x[Use-24]
	_ = x[Var-25]
	_ = x[New-26]
	_ = x[Int-27]
	_ = x[Float-28]
	_ = x[String-29]
	_ = x[Bool-30]
	_ = x[Minus-31]
	_ = x[Plus-32]
	_ = x[Slash-33]
	_ = x[Star-34]
	_ = x[Dot-35]
	_ = x[Colon-36]
	_ = x[NewLine-37]
	_ = x[Not-38]
	_ = x[Arrow-39]
	_ = x[Comma-40]
	_ = x[Assign-41]
	_ = x[Equal-42]
	_ = x[NotEqual-43]
	_ = x[Less-44]
	_ = x[LessEqual-45]
	_ = x[Great-46]
	_ = x[GreatEqual-47]
	_ = x[Ident-48]
	_ = x[LeftParen-49]
	_ = x[RightParen-50]
	_ = x[LeftBracket-51]
	_ = x[RightBracket-52]
	_ = x[LeftBrace-53]
	_ = x[RightBrace-54]
}

const _Type_name = "IllegalEOFifisforswitchcasedefaultinstopnextwhileelsefunnonecatchblockobjectreturnsuperorandthisusevarNewIntFloatStringBool-+/*.:\\n!->Comma===!=<<=>>=Ident()[]{}"

var _Type_index = [...]uint8{0, 7, 10, 12, 14, 17, 23, 27, 34, 36, 40, 44, 49, 53, 56, 60, 65, 70, 76, 82, 87, 89, 92, 96, 99, 102, 105, 108, 113, 119, 123, 124, 125, 126, 127, 128, 129, 131, 132, 134, 139, 140, 142, 144, 145, 147, 148, 150, 155, 156, 157, 158, 159, 160, 161}

func (i Type) String() string {
	i -= 1
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
