name: Pipeline

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Run lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.46.2

    - name: Run tests
      run: go test -race -v ./...

    - name: Build
      run: go build -o iracema cmd/iracema/main.go

